# Generated by Django 3.2 on 2022-10-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('germany', 'GERMAN'), ('hindi', 'HINDI')], max_length=10),
        ),
    ]
