# Generated by Django 3.2 on 2022-10-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('hindi', 'HINDI'), ('telugu', 'TELUGU'), ('tamil', 'TAMIL')], max_length=10),
        ),
    ]
